{% set name = "esp-lab" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esp-lab-{{ version }}.tar.gz
  sha256: 8143425e3503007d16013e5460411fc6b33de00c9a442042413d4045e9f3329d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - python >=3.8

test:
  imports:
    - esp_lab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://esp-lab.readthedocs.io
  summary: Utilities for SMYLE Analysis
  dev_url: https://github.com/CESM-ESPWG/ESP-Lab
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - Teagan
